//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRCRAFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRCRAFT()
        {
            this.FLIGHTs = new HashSet<FLIGHT>();
        }
    
        public string AIRCRAFTID { get; set; }
        public string ADMINID { get; set; }
        public string ADM_ADMINID { get; set; }
        public string AIRCRAFTTYPE { get; set; }
        public string STATUS { get; set; }
        public string AIRCRAFTNAME { get; set; }
        public int CAPACITY { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual ADMIN ADMIN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLIGHT> FLIGHTs { get; set; }
    }
}
