//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT()
        {
            this.BOOKs = new HashSet<BOOK>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.CUSTOMERs1 = new HashSet<CUSTOMER>();
        }
    
        public string FLIGHTID { get; set; }
        public string ADMINID { get; set; }
        public string AIRCRAFTID { get; set; }
        public string ADM_ADMINID { get; set; }
        public double FARE { get; set; }
        public string ARRIVALDATE { get; set; }
        public string DEPARTUREDATE { get; set; }
        public string SOURCE { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<int> AVAILBLESEATS { get; set; }
        public Nullable<int> TOTALSEATS { get; set; }
        public string AIRCRAFT_ID { get; set; }
        public Nullable<bool> BUSINESS { get; set; }
        public Nullable<bool> ECONOMY { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual ADMIN ADMIN1 { get; set; }
        public virtual AIRCRAFT AIRCRAFT { get; set; }
        public virtual TICKET TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK> BOOKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMERs1 { get; set; }
    }
}
