//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public string FLIGHTID { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<int> SEATNO { get; set; }
        public Nullable<double> DURATION { get; set; }
        public string SOURCE { get; set; }
        public Nullable<int> TICKETNO { get; set; }
        public string FLIGHT_ID { get; set; }
    
        public virtual FLIGHT FLIGHT { get; set; }
    }
}
